{
 "title": "App Observability Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Traces jaeger",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "service": "sample-app" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "app_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "app-logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app-logs\"} |= \"INFO\"\r\n\r\n"
    }
   ]
  },
  {
   "title": "prometheus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (path, method, status) (rate(app_requests_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}